### ISSUE TITLE
关于t-SNE的问题

### ISSUE THREAD

**Issue by shenao1995** [Cherishzyh/ProstrateECE#1]
您好！最近我正在阅读您的《Artificial intelligence is a promising prospect for the detection of prostate cancer extracapsular extension with mpMRI: a two-center comparative study》这篇论文，我发现您运用到t-SNE来可视化网络的性能，但是我在使用t-SNE比较网络性能时，不同的网络数据分布会出现随机的情况，这样从视觉上就难以对比了，我看您文章中的图两个网络的t-SNE分布是相同的，想问您一下是怎么解决这个问题的。

**Comment by Cherishzyh** [comment]
您好！我这边看了一下之前自己基于python使用sklearn.manifold.TSNE这个函数对两个模型画的TSNE图，分布是一致的。文章中的TSNE图是医生那边使用R语言画的，您可以参考一下。

**Comment by shenao1994** [comment]
谢谢您的回复！可以再请教一下您的参数是怎么设置的吗？`tsne = TSNE(n_components=2, random_state=1).fit_transform(our_features)`我只固定了随机种子，同一个网络跑多次，分布确实是一样的，但换别的网络后，分布就会变，非常奇怪，数据也是固定的。

**Comment by shenao1995** [comment]
> 您好！我这边看了一下之前自己基于python使用sklearn.manifold.TSNE这个函数对两个模型画的TSNE图，分布是一致的。文章中的TSNE图是医生那边使用R语言画的，您可以参考一下。

谢谢您的回复！可以再请教一下您的参数是怎么设置的吗？`tsne = TSNE(n_components=2, random_state=1).fit_transform(our_features)`我只固定了随机种子，同一个网络跑多次，分布确实是一样的，但换别的网络后，分布就会变，非常奇怪，数据也是固定的。

**Comment by Cherishzyh** [comment]
我用的是tsne = TSNE(perplexity=30, n_components=2, init='pca', n_iter=5000)，然后我刚刚试了试您给的参数，也会出现分布不相同的情况，可能是跟init的参数相关，我加了之后分布就相似了。

**Comment by Cherishzyh** [comment]
>

**Comment by shenao1995** [comment]
好的，非常感谢您的解答！
祝好！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Cherishzyh/ProstateECE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月2日(星期四) 下午2:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Cherishzyh/ProstateECE] 关于t-SNE的问题 (Issue #1)





 
我用的是tsne = TSNE(perplexity=30, n_components=2, init='pca', n_iter=5000)，然后我刚刚试了试您给的参数，也会出现分布不相同的情况，可能是跟init的参数相关，我加了之后分布就相似了。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
